### ISSUE TITLE
Wrong link about the details of the Virus

### ISSUE THREAD

**Issue by ismaail** [elmehdiabdi-src/coronanews-srcx#2]
The tab **توجيهات** shows the link this page

[فيروس كورونا المسبب لمتلازمة الشرق الأوسط التنفسية (فيروس كورونا)](https://www.who.int/features/qa/mers-cov/ar/)

--

I think the correct link should be

[مرض فيروس كورونا (كوفيد-19)](https://www.who.int/ar/emergencies/diseases/novel-coronavirus-2019/advice-for-public/q-a-coronaviruses)
or
[فيروس كورونا المستجد (2019-nCoV)](https://www.who.int/ar/emergencies/diseases/novel-coronavirus-2019)

**Comment by El-Mehdi-Abdi** [comment]
فيروس كورونا المسبب لمتلازمة الشرق الأوسط التنفسية (فيروس كورونا)

kat3ni ra badat mn la chine had title katbah monadamt siha

**Comment by ismaail** [comment]
The website is about COVID-19, so it should give information about the correct subject.

There is so many [Coronaviruses](https://en.wikipedia.org/wiki/Coronavirus):
- Human coronavirus 229E (HCoV-229E)
- Human coronavirus OC43 (HCoV-OC43)
- Severe acute respiratory syndrome coronavirus (SARS-CoV)
- Human coronavirus NL63 (HCoV-NL63, New Haven coronavirus)
- Human coronavirus HKU1
- Middle East respiratory syndrome-related coronavirus (MERS-CoV)
- Severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2)
